//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LangDef.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace projeto_compiler {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LangDefParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILangDefListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] LangDefParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] LangDefParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] LangDefParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] LangDefParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] LangDefParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] LangDefParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] LangDefParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] LangDefParser.FactorContext context);
}
} // namespace projeto_compiler
