//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LangDef.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace projeto_compiler {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILangDefListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LangDefBaseListener : ILangDefListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] LangDefParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] LangDefParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloco([NotNull] LangDefParser.BlocoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloco([NotNull] LangDefParser.BlocoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd([NotNull] LangDefParser.CmdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd([NotNull] LangDefParser.CmdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmdRead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmdRead([NotNull] LangDefParser.CmdReadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmdRead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmdRead([NotNull] LangDefParser.CmdReadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmdWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmdWrite([NotNull] LangDefParser.CmdWriteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmdWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmdWrite([NotNull] LangDefParser.CmdWriteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmdAttr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmdAttr([NotNull] LangDefParser.CmdAttrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmdAttr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmdAttr([NotNull] LangDefParser.CmdAttrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] LangDefParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] LangDefParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] LangDefParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] LangDefParser.TermContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace projeto_compiler
