//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LangDef.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace projeto_compiler {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LangDefParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILangDefListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] LangDefParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] LangDefParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloco([NotNull] LangDefParser.BlocoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloco([NotNull] LangDefParser.BlocoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd([NotNull] LangDefParser.CmdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd([NotNull] LangDefParser.CmdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmdRead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmdRead([NotNull] LangDefParser.CmdReadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmdRead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmdRead([NotNull] LangDefParser.CmdReadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmdWrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmdWrite([NotNull] LangDefParser.CmdWriteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmdWrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmdWrite([NotNull] LangDefParser.CmdWriteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.cmdAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmdAttr([NotNull] LangDefParser.CmdAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.cmdAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmdAttr([NotNull] LangDefParser.CmdAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] LangDefParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] LangDefParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangDefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] LangDefParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangDefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] LangDefParser.TermContext context);
}
} // namespace projeto_compiler
